services:
    # Laravel with PHP 8.4
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: stock_reports_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - mysql
            - redis
        networks:
            - laravel

    # Nginx for Laravel
    nginx:
        image: nginx:latest
        container_name: stock_reports_nginx
        restart: unless-stopped
        ports:
            - "${FORWARD_APP_PORT:-8084}:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    # MySQL 8
    mysql:
        image: mysql:8
        container_name: stock_reports_mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "${FORWARD_DB_PORT:-3308}:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel

    # Redis for caching & queues
    redis:
        image: redis:latest
        container_name: stock_reports_redis
        restart: unless-stopped
        ports:
            - "${FORWARD_REDIS_PORT:-6381}:6379"
        networks:
            - laravel

    # MailHog for email testing
    mailhog:
        image: mailhog/mailhog
        container_name: stock_reports_mailhog
        restart: unless-stopped
        ports:
            - "${FORWARD_MAILHOG_DASHBOARD_PORT:-8026}:8025"  # Web UI
            - "${FORWARD_MAILHOG_PORT:-1026}:1025"  # SMTP Server
        networks:
            - laravel

    # Vite
    vite:
        image: node:20
        container_name: stock_reports_vite
        working_dir: /var/www
        volumes:
            - .:/var/www
        command: sh -c "npm install && npm run dev"
        ports:
            - "5173:5173" # default Vite port
        depends_on:
            - app
        networks:
            - laravel

    # Laravel Echo Server
    echo-server:
        image: node:20
        container_name: stock_reports_echo_server
        working_dir: /app
        volumes:
            - ./:/app
        command: >
            sh -c "npm install -g laravel-echo-server &&
                   cp laravel-echo-server.json /root &&
                   laravel-echo-server start --dir=/root --force"
        ports:
            - "${FORWARD_LARAVEL_ECHO_SERVER_PORT:-6001}:6001"
        depends_on:
            - app
            - redis
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    mysql_data:
